// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzfbvejuiwrdtjbonsqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6ZmJ2ZWp1aXdyZHRqYm9uc3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNjE5MDQsImV4cCI6MjA1NDYzNzkwNH0.oXQ50k18CW1tpY3YqLN8iIGmO4Q76yJGNNRnqKjj6H0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);